### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'accounts')

### ISSUE THREAD

**Issue by agriffis** [nathonius/obsidian-github-link#104]
Hi! Just trying this plugin and ran into:

![image](https://github.com/nathonius/obsidian-github-link/assets/50637/f31d72f5-78d8-40ef-b5d7-feaa78d980bc)

**Comment by agriffis** [comment]
Since this is happening when the plugin loads, there's no opportunity to set any settings.

**Comment by agriffis** [comment]
I'm running Obsidian 1.5.12

**Comment by agriffis** [comment]
To work around this for now, I created `.obsidian/plugins/github-link/data.json` in my vault with the content `{}`

**Comment by agriffis** [comment]
Might be fixed by #105

**Comment by nathonius** [comment]
Sorry you ran into that! The perils of not testing with a fresh install I guess.

**Comment by nathonius** [comment]
Fix released in v0.7.1. Thanks again!
