### ISSUE TITLE
Support issues for org as simple query

### ISSUE THREAD

**Issue by agriffis** [nathonius/obsidian-github-link#114]
I've tried a bunch of combinations from the docs, but I can't seem to get a list of issues confined to an organization. If I leave out `filter:` then I only get stuff that's assigned to me, and if I add `filter:` then issues from other organizations start to show up in the results.

Here is my base query. Any suggestions?

```
outputType: table
queryType: issue
org: myorganization
sort: updated
per_page: 8
columns: [repo, number, title, created, updated]
```

**Comment by nathonius** [comment]
Just querying for issues from a specific org/user isn't currently supported as a simple query, but could probably be added. At this point its restricted to org + repo.

For a custom query this works:

For a user:
````
```github-query
outputType: table
queryType: issue
query: user:nathonius type:issue
columns: [repo, number, title, created, updated]
```
````

For an org:
````
```github-query
outputType: table
queryType: issue
query: org:cli type:issue
columns: [repo, number, title, created, updated]
```
````

**Comment by agriffis** [comment]
Cool, thanks! This is working for me:

```
outputType: table
queryType: issue
query: org:myorganization
sort: updated
per_page: 8
columns: [repo, number, title, created, updated]
```

except that the "View on GitHub" link searches code, rather than issue or prs.
