### ISSUE TITLE
Clicking github link tags in popout windows closes window

### ISSUE THREAD

**Issue by anissa111** [nathonius/obsidian-github-link#115]
Great plugin! I'm experiencing an issue with the links from the preview tags in pop windows

See:

https://github.com/nathonius/obsidian-github-link/assets/38434768/c9923cd8-7464-49ea-a792-b1d39da86a57

Only happens in pop out windows.

**Comment by anissa111** [comment]
Update: happens when clicking links in `github-query` tables, too

**Comment by nathonius** [comment]
Probably just need to set the right rel tag on them. Will fix.

**Comment by nathonius** [comment]
@anissa111 apologies for the delay. Should be fixed in v0.7.2.
