### ISSUE TITLE
Add missing "Supported Columns" to the documentation

### ISSUE THREAD

**Issue by claremacrae** [nathonius/obsidian-github-link#118]
The table in [Codeblock reference](https://github.com/obsidian-tasks-group/obsidian-tasks/pulls?q=is%3Apr+is%3Aopen+-is%3Adraft+status%3Asuccess) says "See Supported Columns list below." but searching for `support` and `column` doesn't find such a list...

![image](https://github.com/nathonius/obsidian-github-link/assets/4840096/3fbd5171-01c0-4443-ac1b-5d0b3aa5a4ae)

**Comment by nathonius** [comment]
Added.
