### ISSUE TITLE
feat: Toggle checkbox state based on issue or PR state

### ISSUE THREAD

**Issue by nikclayton** [nathonius/obsidian-github-link#67]
At the moment if I write:

```
- [ ] https://github.com/nathonius/obsidian-github-link/issues/1
```

the plugin renders the chip including the repository name and the issue title, but the state of the issue (or PR) is not reflected in the state of the checkbox.

It would be great (I have no idea if the Obsidian API supports this) if in this case the checkbox became readonly, and the state of the checkbox reflected the state of the issue or PR (checked if it's closed, unchecked if it's still open).

**Comment by nathonius** [comment]
Interesting. I'm not entirely sure how this would work. Right now the plugin doesn't actually make any modifications to the underlying markdown content of notes, it only replaces the rendered output.

It seems like this would require changing the underlying file, which I'm very wary of doing.

Can you give some more details about your workflow? Perhaps there's another way to accomplish what you're trying to do.

**Comment by nikclayton** [comment]
> Can you give some more details about your workflow? Perhaps there's another way to accomplish what you're trying to do.

I'm trying to use things like the tasks plugin to get an overall view of todo-list items, and an open issue is a todo-item (something like "Check in on issue #x to see if it's been resolved / needs more input", etc.

But if the issue (or PR) has been closed on GitHub then I don't need to do that, so the associated task could automatically be marked as done.

I appreciate that this would a bit of a shift in focus for this plugin, making it more of a workflow tool than just a cosmetic enhancement, and it's obviously perfectly fine if that's not a route you want to go down.

**Comment by nathonius** [comment]
I'm going to go ahead and close this one. This is really just outside the scope of what this plugin is intended for. I really don't want to get into the business of modifying the on-disk content of notes.
