### ISSUE TITLE
add option to show namespaces

### ISSUE THREAD

**Issue by GottZ** [nathonius/obsidian-github-link#80]
![image](https://github.com/nathonius/obsidian-github-link/assets/559564/06f8700b-a537-4a18-bb82-6e29420d8420)
two namespaces, same repo name.

it would be nice to have a toggle that also displays the namespace in front of the repository name.

**Comment by nathonius** [comment]
Great point! Plus working on open source repos lends itself to forks.

I'm curious - are those just links directly to the repos, not specific issues or PRs?

**Comment by GottZ** [comment]
> Great point! Plus working on open source repos lends itself to forks.

and creating issues tends to lead towards product improvements.
I tend to also create pull requests but in this case I had to go to bed.

> I'm curious - are those just links directly to the repos, not specific issues or PRs?

yes indeed. I have a couple link collection notes and just noticed it when scrolling through.
I have also thrown yesterday's GitHub interactions into my primary index, which is what guided me to this answer today :)
now that I think about it, making it possible to see the last comment author name could be another viable feature..
I'll dig into that later.

**Comment by nathonius** [comment]
@GottZ available in v0.7.0
